#!/usr/bin/env python3
"""Build a TMLR-formatted PDF of the manuscript (plan task P3).

Reuses the markdown -> pandoc body conversion from the paper's own
``manuscript_negative/build.py`` but swaps the draft preamble for the TMLR
style (``jmlr.cls`` + ``tmlr.sty``; both are present in the local TeX Live, and
``tmlr.sty`` is vendored next to the output so the build is self-contained).

    python docs/paper_patch/make_tmlr.py --body-only   # just write the .tex
    python docs/paper_patch/make_tmlr.py               # write + compile

Outputs ``manuscript_negative/tmlr/negative-result-tmlr.{tex,pdf}``; the draft
build (``build.py``) is untouched.
"""
from __future__ import annotations

import argparse
import os
import pathlib
import shutil
import subprocess
import sys

CODE = pathlib.Path(__file__).resolve().parents[2]      # <repo>/docs/paper_patch
PAPER_REPO = pathlib.Path(os.environ.get("APC_PAPER_DIR", CODE.parent / "02_apc_paper"))
PAPER = PAPER_REPO
MANU = PAPER / "manuscript_negative"
OUT_DIR = MANU / "tmlr"
STYLE_SRC = (
    "https://raw.githubusercontent.com/JmlrOrg/tmlr-style-file/master/tmlr.sty")

TITLE = ("Validation Argmax Is Hard to Beat: A Pre-Registered Negative Result "
         "on Structured Deployment Gates for Prompt Compilation")

PREAMBLE = r"""% jmlr.cls loads hyperref itself, so pass our option before the class.
\PassOptionsToPackage{hidelinks}{hyperref}
\documentclass[tmlr]{jmlr}
% TMLR submission build of negative-result.md.  Generated by
% code/docs/paper_patch/make_tmlr.py -- edit the markdown, not this file.
\usepackage{tmlr}
\usepackage[T1]{fontenc}
\usepackage{times,amsmath,amssymb}
\usepackage{booktabs,longtable,array,multirow,calc}
\usepackage{graphicx,microtype,url,xcolor,textcomp}
% The manuscript carries its own section numbers in the headings; keep them.
\setcounter{secnumdepth}{0}
\sloppy
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\title{%TITLE%}
\author{Anonymous Authors}
\begin{document}
\maketitle
"""


# Inline identifiers used in the manuscript -> BibTeX keys in vendor/references.bib.
# natbib prints author-year, so the surrounding prose is unchanged.
CITE_MAP = [
    ("(Feurer et al., NeurIPS 2015)", " \\citep{feurer2015autosklearn}"),
    ("(1603.06560)", " \\citep{li2018hyperband}"),
    ("(1807.01774)", " \\citep{falkner2018bohb}"),
    ("(1611.01578)", " \\citep{zoph2017nas}"),
    ("(1703.03400)", " \\citep{finn2017maml}"),
    ("(1908.00709)", " \\citep{he2019automlsurvey}"),
    ("(1907.06902)", " \\citep{dacrema2019worrying}"),
    ("(1709.06560)", " \\citep{henderson2018matters}"),
    ("(1909.03004)", " \\citep{wang2019showyourwork}"),
]


def to_bibtex_citations(body: str) -> tuple[str, int]:
    """Rewrite ``(1603.06560)``-style mentions into natbib citations."""
    n = 0
    for old, new in CITE_MAP:
        if old in body:
            n += body.count(old)
            body = body.replace(old, new)
    return body, n


def to_bibliography(body: str) -> str:
    """Swap the hand-written reference list for ``\bibliography{references}``.

    The markdown keeps a plain numbered list so the draft build needs no BibTeX;
    the TMLR build replaces that block (which pandoc emits as its own section,
    between ``References`` and the appendix) with a generated one.
    """
    start = body.find("\\section{References}")
    if start < 0:
        return body
    nxt = body.find("\\section{", start + 1)
    end = len(body) if nxt < 0 else nxt
    return (body[:start]
            + "\\bibliographystyle{tmlr}\n\\bibliography{references}\n\n"
            + body[end:])


def ensure_style() -> pathlib.Path:
    r"""Make sure a *patched* tmlr.sty sits next to the .tex.

    TeX Live's jmlr.cls already defines four title-spacing lengths that upstream
    tmlr.sty re-creates with \newlength, so the stock file aborts the build.  We
    ship the two-line guard patch in docs/paper_patch/vendor/tmlr.sty and fall
    back to downloading + patching upstream when the vendored copy is absent.
    """
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    vendor = pathlib.Path(__file__).resolve().parent / "vendor"
    for extra in ("tmlr.bst", "references.bib"):
        target, source = OUT_DIR / extra, vendor / extra
        if source.exists() and (not target.exists()
                                or target.read_bytes() != source.read_bytes()):
            shutil.copy2(source, target)
    dst = OUT_DIR / "tmlr.sty"
    src = vendor / "tmlr.sty"
    if not dst.exists():
        if src.exists():
            shutil.copy2(src, dst)
        else:
            r = subprocess.run(["curl", "-sSL", "-o", str(dst), STYLE_SRC],
                               capture_output=True, text=True, errors="replace")
            if r.returncode or dst.stat().st_size < 2000:
                raise SystemExit(f"could not obtain tmlr.sty ({r.stderr.strip()})")
    s = dst.read_text(encoding="utf-8")
    if r"\@ifundefined{aftertitskip}" not in s:
        unpatched = ("\\newlength\\aftertitskip     \\newlength\\beforetitskip\n"
                     "\\newlength\\interauthorskip  \\newlength\\aftermaketitskip")
        if unpatched not in s:
            raise SystemExit("tmlr.sty has an unexpected layout; review the patch")
        patched = "\n".join(
            f"\\@ifundefined{{{n}}}{{\\newlength\\{n}}}{{}}"
            for n in ("aftertitskip", "beforetitskip", "interauthorskip",
                      "aftermaketitskip"))
        dst.write_text(s.replace(unpatched, patched), encoding="utf-8")
        print("patched freshly downloaded tmlr.sty")
    return dst


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--body-only", action="store_true")
    ap.add_argument("--md", default=str(MANU / "negative-result.md"))
    ap.add_argument("--out", default=None, help="output dir (for dry runs)")
    args = ap.parse_args()
    global OUT_DIR
    if args.out:
        OUT_DIR = pathlib.Path(args.out)

    sys.path.insert(0, str(MANU))
    import build  # the paper's markdown -> latex body pipeline

    md = build.preprocess(pathlib.Path(args.md).read_text(encoding="utf-8"))
    tmp_md = OUT_DIR / ".body.md"
    tmp_tex = OUT_DIR / ".body.tex"
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    tmp_md.write_text(md, encoding="utf-8")
    subprocess.run(["pandoc", "-f", "gfm+tex_math_dollars+smart", "-t", "latex",
                    "--wrap=none", str(tmp_md.resolve()), "-o", str(tmp_tex.resolve())],
                   check=True, env={**os.environ, "TMPDIR": "/tmp"})
    body = tmp_tex.read_text(encoding="utf-8")
    body = build.fix_images(build.decode_dashes(body))
    body = __import__("re").sub(
        r"\\texttt\{([^{}]*)\}",
        lambda m: "\\texttt{" + m.group(1).replace("/", "/\\allowbreak{}")
        .replace("_", "_\\allowbreak{}") + "}", body)
    body = body.replace("@@SECT@@", "\\S{}")
    body, n_cites = to_bibtex_citations(body)
    body = to_bibliography(body)
    print(f"citations: {n_cites} inline identifiers -> \\citep{{}}")
    tex = build.clean_unicode(
        PREAMBLE.replace("%TITLE%", TITLE) + build.lt2tab(body)) + "\n\\end{document}\n"
    out_tex = OUT_DIR / "negative-result-tmlr.tex"
    out_tex.write_text(tex, encoding="utf-8")
    tmp_md.unlink(missing_ok=True)
    tmp_tex.unlink(missing_ok=True)
    print(f"wrote {out_tex} ({len(tex)} chars)")

    ensure_style()
    if args.body_only:
        return 0
    for tool in ("pdflatex", "bibtex"):
        if not shutil.which(tool):
            print(f"{tool} missing -- not compiling", file=sys.stderr)
            return 0

    # Explicit sequence: latexmk's dependency heuristics stop before re-reading a
    # freshly written .bbl, which leaves every \citep as "(?)".  Four fixed passes
    # are slower by a second and deterministic.
    env = {**os.environ, "TMPDIR": "/tmp"}
    pdf = out_tex.with_suffix(".pdf")
    pdf.unlink(missing_ok=True)
    runs = [["pdflatex", "-interaction=nonstopmode", "-halt-on-error", out_tex.name],
            None,  # aux fix-up + bibtex, handled below
            ["pdflatex", "-interaction=nonstopmode", out_tex.name],
            ["pdflatex", "-interaction=nonstopmode", out_tex.name]]
    for cmd in runs:
        if cmd is None:
            # jmlr.cls asks for plainnat.bst in the preamble and the body asks for
            # tmlr.bst; BibTeX refuses two \bibstyle lines ("Illegal, another
            # \bibstyle command") and falls back to the wrong style, which leaves
            # every citation undefined.  Keep the last one -- ours.
            aux = OUT_DIR / f"{out_tex.stem}.aux"
            if aux.exists():
                lines = aux.read_text(encoding="utf-8").splitlines()
                styles = [i for i, l in enumerate(lines) if l.startswith("\\bibstyle")]
                for i in reversed(styles[:-1]):
                    del lines[i]
                aux.write_text("\n".join(lines) + "\n", encoding="utf-8")
                if len(styles) > 1:
                    print(f"aux: dropped {len(styles) - 1} conflicting \\bibstyle line(s)")
            r = subprocess.run(["bibtex", out_tex.stem], cwd=OUT_DIR,
                               capture_output=True, text=True, errors="replace", env=env)
            if r.returncode != 0:
                print("bibtex failed", file=sys.stderr)
                print((r.stdout or "")[-2000:], file=sys.stderr)
                return r.returncode
            continue
        r = subprocess.run(cmd, cwd=OUT_DIR, capture_output=True, text=True, errors="replace", env=env)
        if r.returncode != 0:
            print(f"{cmd[0]} failed (exit {r.returncode})", file=sys.stderr)
            print((r.stdout or "")[-3000:], file=sys.stderr)
            return r.returncode
    if not pdf.exists():
        print("no PDF produced", file=sys.stderr)
        return 1
    log = (OUT_DIR / f"{out_tex.stem}.log").read_text(encoding="utf-8", errors="ignore")
    if "There were undefined citations" in log:
        print("warning: undefined citations remain in the TMLR build", file=sys.stderr)
    info = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True, errors="replace")
    pages = next((l.split()[-1] for l in info.stdout.splitlines()
                  if l.startswith("Pages")), "?")
    print(f"wrote {pdf} ({pages} pages)")
    # keep the .bbl (submissions are often compiled without BibTeX), drop the rest
    for pat in ("*.aux", "*.log", "*.fls", "*.fdb_latexmk", "*.out", "*.blg"):
        for f in OUT_DIR.glob(pat):
            f.unlink(missing_ok=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
