#!/usr/bin/env python3
"""Build a TMLR-formatted PDF of the manuscript (plan task P3).

Reuses the markdown -> pandoc body conversion from the paper's own
``manuscript_negative/build.py`` but swaps the draft preamble for the TMLR
style (``jmlr.cls`` + ``tmlr.sty``; both are present in the local TeX Live, and
``tmlr.sty`` is vendored next to the output so the build is self-contained).

    python docs/paper_patch/make_tmlr.py --body-only   # just write the .tex
    python docs/paper_patch/make_tmlr.py               # write + compile

Outputs ``manuscript_negative/tmlr/negative-result-tmlr.{tex,pdf}``; the draft
build (``build.py``) is untouched.
"""
from __future__ import annotations

import argparse
import os
import pathlib
import shutil
import subprocess
import sys

CODE = pathlib.Path(__file__).resolve().parents[2]      # <repo>/docs/paper_patch
PAPER_REPO = pathlib.Path(os.environ.get("APC_PAPER_DIR", CODE.parent / "02_apc_paper"))
PAPER = PAPER_REPO
MANU = PAPER / "manuscript_negative"
OUT_DIR = MANU / "tmlr"
STYLE_SRC = (
    "https://raw.githubusercontent.com/JmlrOrg/tmlr-style-file/master/tmlr.sty")

TITLE = ("Validation Argmax Is Hard to Beat: A Pre-Registered Negative Result "
         "on Structured Deployment Gates for Prompt Compilation")

PREAMBLE = r"""% jmlr.cls loads hyperref itself, so pass our option before the class.
\PassOptionsToPackage{hidelinks}{hyperref}
\documentclass[tmlr]{jmlr}
% TMLR submission build of negative-result.md.  Generated by
% code/docs/paper_patch/make_tmlr.py -- edit the markdown, not this file.
\usepackage{tmlr}
\usepackage[T1]{fontenc}
\usepackage{times,amsmath,amssymb}
\usepackage{booktabs,longtable,array,multirow,calc}
\usepackage{graphicx,microtype,url,xcolor,textcomp}
% The manuscript carries its own section numbers in the headings; keep them.
\setcounter{secnumdepth}{0}
\sloppy
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\title{%TITLE%}
\author{Anonymous Authors}
\begin{document}
\maketitle
"""


def ensure_style() -> pathlib.Path:
    """tmlr.sty must sit next to the .tex for latexmk to find it."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    dst = OUT_DIR / "tmlr.sty"
    if dst.exists() and dst.stat().st_size > 2000:
        return dst
    r = subprocess.run(["curl", "-sSL", "-o", str(dst), STYLE_SRC],
                       capture_output=True, text=True)
    if r.returncode or dst.stat().st_size < 2000:
        raise SystemExit(f"could not obtain tmlr.sty ({r.stderr.strip()})")
    return dst


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--body-only", action="store_true")
    ap.add_argument("--md", default=str(MANU / "negative-result.md"))
    ap.add_argument("--out", default=None, help="output dir (for dry runs)")
    args = ap.parse_args()
    global OUT_DIR
    if args.out:
        OUT_DIR = pathlib.Path(args.out)

    sys.path.insert(0, str(MANU))
    import build  # the paper's markdown -> latex body pipeline

    md = build.preprocess(pathlib.Path(args.md).read_text(encoding="utf-8"))
    tmp_md = OUT_DIR / ".body.md"
    tmp_tex = OUT_DIR / ".body.tex"
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    tmp_md.write_text(md, encoding="utf-8")
    subprocess.run(["pandoc", "-f", "gfm+tex_math_dollars+smart", "-t", "latex",
                    "--wrap=none", str(tmp_md.resolve()), "-o", str(tmp_tex.resolve())],
                   check=True, env={**os.environ, "TMPDIR": "/tmp"})
    body = tmp_tex.read_text(encoding="utf-8")
    body = build.fix_images(build.decode_dashes(body))
    body = __import__("re").sub(
        r"\\texttt\{([^{}]*)\}",
        lambda m: "\\texttt{" + m.group(1).replace("/", "/\\allowbreak{}")
        .replace("_", "_\\allowbreak{}") + "}", body)
    body = body.replace("@@SECT@@", "\\S{}")
    tex = build.clean_unicode(
        PREAMBLE.replace("%TITLE%", TITLE) + build.lt2tab(body)) + "\n\\end{document}\n"
    out_tex = OUT_DIR / "negative-result-tmlr.tex"
    out_tex.write_text(tex, encoding="utf-8")
    tmp_md.unlink(missing_ok=True)
    tmp_tex.unlink(missing_ok=True)
    print(f"wrote {out_tex} ({len(tex)} chars)")

    ensure_style()
    if args.body_only:
        return 0
    if not shutil.which("latexmk"):
        print("latexmk missing -- not compiling", file=sys.stderr)
        return 0
    r = subprocess.run(["latexmk", "-pdf", "-interaction=nonstopmode",
                        "-halt-on-error", out_tex.name],
                       cwd=OUT_DIR, capture_output=True, text=True,
                       env={**os.environ, "TMPDIR": "/tmp"})
    if r.returncode != 0:
        print(r.stdout[-3000:], file=sys.stderr)
        return r.returncode
    pdf = out_tex.with_suffix(".pdf")
    info = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True)
    pages = next((l.split()[-1] for l in info.stdout.splitlines()
                  if l.startswith("Pages")), "?")
    print(f"wrote {pdf} ({pages} pages)")
    for pat in ("*.aux", "*.log", "*.fls", "*.fdb_latexmk", "*.out", "*.bbl", "*.blg"):
        for f in OUT_DIR.glob(pat):
            f.unlink(missing_ok=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
