#!/usr/bin/env python
"""Render the P3 results as LaTeX fragments for the paper (plan task P1/P2).

Reads ``jev_rsi/results/jev_rsi_extended_results.json`` and
``jev_rsi/results/jev_rsi_extended_analysis.json`` (both produced by real runs)
and emits the main-results table plus the three scenario paragraphs.  The paper
repository is outside this code repository, so the fragments are written next to
the results for a human to paste.

    cd code && python scripts/p3_paper_tables.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "jev_rsi" / "results"
OUT = RESULTS / "p3_paper_tables.tex"

SCEN = {"original": "Original corpus", "scenario_a": "Scenario A (judge variance)",
        "scenario_b": "Scenario B (multi-modal)", "scenario_c": "Scenario C (adversarial)"}


def fmt(s: dict) -> str:
    return f"{s['exact_oracle']}/{s['n_groups']}"


def main() -> int:
    res = json.loads((RESULTS / "jev_rsi_extended_results.json").read_text(encoding="utf-8"))
    ana = json.loads((RESULTS / "jev_rsi_extended_analysis.json").read_text(encoding="utf-8"))
    per = ana["per_scenario"]
    ds = ana["dataset"]

    L: list[str] = []
    L.append("% Auto-generated by scripts/p3_paper_tables.py -- do not edit by hand.")
    L.append("% Source: jev_rsi/results/jev_rsi_extended_{results,analysis}.json")
    L.append("")
    L.append("\\begin{table}[t]")
    L.append("\\centering")
    L.append(f"\\caption{{Main results on the extended corpus "
             f"({ds['n_total']} groups: {ds['n_frozen']} frozen APC + "
             f"{ds['n_extended']} P3). Cells are exact-oracle / decision groups, "
             f"with average holdout regret.}}")
    L.append("\\label{tab:p3-main}")
    L.append("\\begin{tabular}{lrrrr}")
    L.append("\\toprule")
    L.append("Corpus & greedy & heuristic & Jev (static) & Jev (LOO-RSI) \\\\")
    L.append("\\midrule")
    for scen in ("original", "scenario_a", "scenario_b", "scenario_c"):
        row = per.get(scen)
        if not row or not row.get("n_decision_groups"):
            continue
        loo = row.get("loo_rsi")
        L.append(f"{SCEN[scen]} ({row['n_decision_groups']}) & "
                 f"{fmt(row['greedy'])} ({row['greedy']['avg_regret']:+.3f}) & "
                 f"{fmt(row['heuristic'])} ({row['heuristic']['avg_regret']:+.3f}) & "
                 f"{fmt(row['jev_static'])} ({row['jev_static']['avg_regret']:+.3f}) & "
                 + (f"{fmt(row['loo_rsi'])} ({row['loo_rsi']['avg_regret']:+.3f})"
                    if loo else "--")
                 + " \\\\")
    L.append("\\midrule")
    mt = res["main_table"]["policies"]
    L.append(f"\\textbf{{Total decision groups "
             f"({ds['n_decision_total']})}} & "
             f"{fmt(mt['greedy']['decision'])} & {fmt(mt['heuristic']['decision'])} & "
             f"{fmt(mt['jev_static']['decision'])} & -- \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    L.append("")

    bc = ana["boundary_conditions"]["by_scenario"]
    L.append("% ---- Results subsections ----")
    L.append("\\subsection{Extended Corpus: Adversarial Val--Holdout Decoupling}")
    c = ana["scenario_c"]
    if c.get("available"):
        L.append(f"We constructed {c['n_groups']} summarisation groups whose gaming arms "
                 f"(keyword-stuffed, template-filled, random-highlight) score low on "
                 f"ROUGE-L F1 against the CNN/DailyMail human highlights, while the "
                 f"baseline-rescaled BERTScore F1 of the same arms averages "
                 f"{c['arms'].get('keyword_stuffed', {}).get('mean_holdout', float('nan')):.3f} "
                 f"versus {c['arms'].get('abstractive', {}).get('mean_holdout', float('nan')):.3f} "
                 f"for honest abstractive summaries. The val ranking therefore never "
                 f"selects a gaming arm "
                 f"({c['n_groups_captured_by_gaming']}/{c['n_groups']} groups), and the "
                 f"hypothesised anti-gaming advantage of structured gating has no room to "
                 f"appear. Boundary conditions: "
                 f"{bc.get('scenario_c', {})}.")
    L.append("")
    L.append("\\subsection{Extended Corpus: High-Variance Judge}")
    a = ana["scenario_a"]
    if a.get("available"):
        L.append(f"{a['n_groups']} creative-writing groups, each arm judged once for val "
                 f"and five times for holdout. Mean per-arm judge standard deviation is "
                 f"{a['mean_judge_std_10']:.2f} (0-10 scale); "
                 f"{a['n_high_variance_groups']}/{a['n_groups']} groups exceed 2.0. "
                 f"Spearman(variance, greedy regret) = "
                 f"{a['spearman_variance_vs_greedy_regret']:+.3f}. The gate left the "
                 f"val-argmax in {a['n_groups'] - a['n_gate_retreats']}/{a['n_groups']} "
                 f"groups. Boundary conditions: {bc.get('scenario_a', {})}.")
    L.append("")
    L.append("\\subsection{Extended Corpus: Multi-Modal Alignment}")
    b = ana["scenario_b"]
    if b.get("available"):
        L.append(f"{b['n_groups']} Flickr30k captioning groups. A text-only judge that sees "
                 f"the human references (val) is compared with a vision judge that sees the "
                 f"image (holdout). Mean Spearman(val, holdout) = "
                 f"{b['mean_val_holdout_spearman']:+.3f}; the val-argmax is a "
                 f"poetic/verbose/child-like caption while the vision-best caption is "
                 f"factual/technical/concise in "
                 f"{b['n_groups_captured_by_poetic']}/{b['n_groups']} groups. "
                 f"Boundary conditions: {bc.get('scenario_b', {})}.")
    L.append("")
    L.append("% ---- Discussion fragment ----")
    total_w = sum(1 for r in ana["boundary_conditions"]["wins"])
    total_l = sum(1 for r in ana["boundary_conditions"]["losses"])
    L.append(f"% Jev-static vs val-argmax over all {ds['n_decision_total']} decision "
             f"groups: wins={total_w}, losses={total_l}.")
    L.append("% Calibration: " + json.dumps(ana["calibration"], ensure_ascii=False))
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    print(f"\nwrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
